### PR TITLE
FASTA indexing and slicing functionalities

### PR DESCRIPTION
**Pull request by NickRoz1**
Hello!

Using awesome [emi80's](https://github.com/emi80) [contributions](https://github.com/biod/BioD/tree/master/bio/std/file), I've included FASTA indexing and slicing functionalities to Sambamba. As BioD submodule was detached since 28ed6e382e commit, merging this pull request will also require either updating BioD version, or manually including [fasta.d](https://github.com/biod/BioD/blob/master/bio/std/file/fasta.d) and [fai.d](https://github.com/biod/BioD/blob/master/bio/std/file/fai.d) into **sambamba/BioD/bio/std/file**

### CODE REVIEW

**Comment by george-githinji** [comment]
just a note, @emi80 contribution has already been merged in BioD master branch.

**Comment by pjotrp** [comment]
Yes, sorry, we are still organising BioD and synchronising with sambamba. Should fix soon (I am building ldc 1.14 first). We should synchronize after.

**Comment by pjotrp** [comment]
@NickRoz1 great work, btw!

**Comment by ycl6** [comment]
Hi, just wondering if the FASTA indexing functionality will be added in the near future?

**Comment by pjotrp** [comment]
We should merge it. @NickRoz1 or @emi80 do you want to add a few test files? Without tests it is probably not a great idea to merge. I think there are some tests in BioD. I can have a look.

**Comment by NickRoz1** [comment]
For `slice.d` - I think it would be better to edit `fastaRegions` function to make it possible to specify FASTA index file separately, e.g.:
```d
auto fastaRegions(string filename, string pathToIndex, string[] queries) {
    File f = File(filename);
    FaiRecord[string] index = makeIndex(readFai(pathToIndex));
    Region[] regions = to!(Region[])(queries);
    return fetchFastaRegions(f, index, regions);
}
```
Instead of:
```d
auto fastaRegions(string filename, string[] queries) {
    File f = File(filename);
    FaiRecord[string] index = makeIndex(readFai(filename~=".fai"));
    Region[] regions = to!(Region[])(queries);
    return fetchFastaRegions(f, index, regions);
}
```

>I think there are some tests in BioD. I can have a look.

There are tests for underlying FASTA parsers, for example: https://github.com/biod/BioD/blob/7969eb0a847b05874e83ffddead26e193ece8101/bio/std/file/fai.d#L133

**Comment by pjotrp** [comment]
Thank you @NickRoz1 !

**Pull request merged**
